# Generated by Django 2.2.6 on 2019-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0002_bonustransaction_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonustransaction',
            name='date_updated',
            field=models.DateField(editable=False, null=True),
        ),
    ]
