# Generated by Django 2.2.6 on 2019-11-17 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_bonustransaction_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustransaction',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
