# Generated by Django 2.2.6 on 2019-11-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0004_auto_20191117_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonustransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='account_payment',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='bonus.AccountPayment'),
        ),
    ]
