# Generated by Django 2.2.6 on 2019-11-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0005_auto_20191117_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustransaction',
            name='account_payment',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bonus.AccountPayment'),
        ),
    ]
