# Generated by Django 2.2.6 on 2019-11-17 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0007_auto_20191117_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonustransaction',
            name='uid',
            field=models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='account_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bonus.AccountPayment'),
        ),
    ]
