# Generated by Django 2.2.6 on 2019-11-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0008_auto_20191117_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonustransaction',
            old_name='uid',
            new_name='id',
        ),
    ]
